mf_id = "letter_0289.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1935-02-23]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0289_001" = "https://www.monacensia-digital.de/i3f/v20/415358"
"letter_0289_002" = "https://www.monacensia-digital.de/i3f/v20/415359"
"letter_0289_003" = "https://www.monacensia-digital.de/i3f/v20/415360"

