mf_id = "letter_0034.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0034_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587709-BCUL-PREVIEW-426387_0001.jpg"
"letter_0034_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587709-BCUL-PREVIEW-426387_0002.jpg"
"letter_0034_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587709-BCUL-PREVIEW-426387_0003.jpg"
"letter_0034_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587709-BCUL-PREVIEW-426387_0004.jpg"
"letter_0034_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587709-BCUL-PREVIEW-426387_0005.jpg"
