mf_id = "letter_0416.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Unbekannt"

[mf_data]
letter_0416_001 = "https://www.e-manuscripta.ch/i3f/v20/5289869/info.json"
letter_0416_002 = "https://www.e-manuscripta.ch/i3f/v20/5289870/info.json"
