mf_id = "letter_0042.json"
mf_lang = "en"
mf_label = "Lettre dactylographiée d'Annemarie Schwarzenbach à Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0042_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587717-BCUL-PREVIEW-426395_0001.jpg"
"letter_0042_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587717-BCUL-PREVIEW-426395_0002.jpg"
"letter_0042_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587717-BCUL-PREVIEW-426395_0003.jpg"
"letter_0042_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587717-BCUL-PREVIEW-426395_0004.jpg"
"letter_0042_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587717-BCUL-PREVIEW-426395_0005.jpg"
