mf_id = "letter_0287.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1933-10-15]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0287_001" = "https://www.monacensia-digital.de/i3f/v20/415351"



