mf_id = "letter_0267.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 17.11.1935"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0267_001" = "https://www.monacensia-digital.de/i3f/v20/415352"
"letter_0267_002" = "https://www.monacensia-digital.de/i3f/v20/415353"

