mf_id = "letter_0294.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1938-03-18]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`


[mf_data]
"letter_0294_001" = "https://www.monacensia-digital.de/i3f/v20/415361"
"letter_0294_002" = "https://www.monacensia-digital.de/i3f/v20/415362"
"letter_0294_003" = "https://www.monacensia-digital.de/i3f/v20/415363"
"letter_0294_004" = "https://www.monacensia-digital.de/i3f/v20/415364"
"letter_0294_005" = "https://www.monacensia-digital.de/i3f/v20/415397"
"letter_0294_006" = "https://www.monacensia-digital.de/i3f/v20/415396"
"letter_0294_007" = "https://www.monacensia-digital.de/i3f/v20/415395"
"letter_0294_008" = "https://www.monacensia-digital.de/i3f/v20/415394"

