mf_id = "letter_0157.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 03.02.1933"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0157_001" = "https://www.monacensia-digital.de/i3f/v20/415581"
"letter_0157_002" = "https://www.monacensia-digital.de/i3f/v20/415582"
