mf_id = "letter_0442.json"
mf_lang = "en"
mf_label = "Brief von Ren√©e Schwarzenbach an Annemarie Schwarzenbach"

[mf_data]
letter_0442_001 = "https://www.e-manuscripta.ch/i3f/v20/5508043/info.json"
letter_0442_002 = "https://www.e-manuscripta.ch/i3f/v20/5508044/info.json"
