mf_id = "letter_0023.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0023_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0001.jpg"
"letter_0023_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0002.jpg"
"letter_0023_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0003.jpg"
"letter_0023_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0004.jpg"
"letter_0023_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0005.jpg"
"letter_0023_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0006.jpg"
"letter_0023_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587697-BCUL-PREVIEW-426375_0007.jpg"


