mf_id = "letter_0254.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 08.07.1935"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0254_001" = "https://www.monacensia-digital.de/i3f/v20/415312"
"letter_0254_002" = "https://www.monacensia-digital.de/i3f/v20/415313"
"letter_0254_003" = "https://www.monacensia-digital.de/i3f/v20/415314"

