mf_id = "letter_0464.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0464_001 = "https://www.e-manuscripta.ch/i3f/v20/5346234/info.json"
letter_0464_002 = "https://www.e-manuscripta.ch/i3f/v20/5346235/info.json"
