mf_id = "letter_0161.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 05.09.1931"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0161_001" = "https://www.monacensia-digital.de/i3f/v20/415746"
"letter_0161_002" = "https://www.monacensia-digital.de/i3f/v20/415747"
