mf_id = "letter_0147.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Seelig, Carl"

[mf_data]
"letter_0147_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0147_001.tif"
"letter_0147_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0147_002.tif"
