mf_id = "letter_0252.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 06.12.1933"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0252_001" = "https://www.monacensia-digital.de/i3f/v20/415285"
"letter_0252_002" = "https://www.monacensia-digital.de/i3f/v20/415286"
"letter_0252_003" = "https://www.monacensia-digital.de/i3f/v20/415287"
"letter_0252_004" = "https://www.monacensia-digital.de/i3f/v20/415288"

