mf_id = "letter_0139.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an McCullers, Carson"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0139_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0139_001.tif"
