mf_id = "letter_0185.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 20.11.1930"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0185_001" = "https://www.monacensia-digital.de/i3f/v20/415561"
"letter_0185_002" = "https://www.monacensia-digital.de/i3f/v20/415562"
"letter_0185_003" = "https://www.monacensia-digital.de/i3f/v20/415563"
