mf_id = "letter_0197.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 8. Juni"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0197_001" = "https://www.monacensia-digital.de/i3f/v20/415552"
"letter_0197_002" = "https://www.monacensia-digital.de/i3f/v20/415553"
