mf_id = "letter_0132.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Fueter, Eduard"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0132_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0132_001.tif"
"letter_0132_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0132_002.tif"
"letter_0132_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0132_003.tif"