mf_id = "letter_0204.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0204_001" = "https://www.monacensia-digital.de/i3f/v20/415612"
"letter_0204_002" = "https://www.monacensia-digital.de/i3f/v20/415613"
"letter_0204_003" = "https://www.monacensia-digital.de/i3f/v20/415614"
"letter_0204_004" = "https://www.monacensia-digital.de/i3f/v20/415615"