mf_id = "letter_0052.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0052_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0001.jpg"
"letter_0052_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0002.jpg"
"letter_0052_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0003.jpg"
"letter_0052_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0004.jpg"
"letter_0052_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0005.jpg"
"letter_0052_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0006.jpg"
"letter_0052_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587727-BCUL-PREVIEW-426405_0007.jpg"


