mf_id = "letter_0454.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0454_001 = "https://www.e-manuscripta.ch/i3f/v20/5346198/info.json"
letter_0454_002 = "https://www.e-manuscripta.ch/i3f/v20/5346199/info.json"
