mf_id = "letter_0037.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0037_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0001.jpg"
"letter_0037_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0002.jpg"
"letter_0037_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0003.jpg"
"letter_0037_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0004.jpg"
"letter_0037_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0005.jpg"
"letter_0037_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0006.jpg"
"letter_0037_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587712-BCUL-PREVIEW-426390_0007.jpg"
