mf_id = "letter_0461.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0461_001 = "https://www.e-manuscripta.ch/i3f/v20/5346222/info.json"
letter_0461_002 = "https://www.e-manuscripta.ch/i3f/v20/5346223/info.json"
letter_0461_003 = "https://www.e-manuscripta.ch/i3f/v20/5346224/info.json"
letter_0461_004 = "https://www.e-manuscripta.ch/i3f/v20/5346225/info.json"
