mf_id = "letter_0091.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0091_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0091_001.tif"
"letter_0091_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0091_002.tif"
"letter_0091_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0091_003.tif"
"letter_0091_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0091_004.tif"
"letter_0091_005" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0091_005.tif"
"letter_0091_006" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0091_006.tif"



