mf_id = "letter_0224.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0224_001" = "https://www.monacensia-digital.de/i3f/v20/415699"
"letter_0224_002" = "https://www.monacensia-digital.de/i3f/v20/415700"
"letter_0224_003" = "https://www.monacensia-digital.de/i3f/v20/415701"
"letter_0224_004" = "https://www.monacensia-digital.de/i3f/v20/415702"


