mf_id = "letter_0413.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Elsy Leuzinger"

[mf_data]
letter_0413_001 = "https://www.e-manuscripta.ch/i3f/v20/5289848/info.json"
letter_0413_002 = "https://www.e-manuscripta.ch/i3f/v20/5289849/info.json"
