
mf_id = "letter_0015.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0015_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587689-BCUL-PREVIEW-426367_0001.jpg"
"letter_0015_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587689-BCUL-PREVIEW-426367_0002.jpg"
"letter_0015_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587689-BCUL-PREVIEW-426367_0003.jpg"
"letter_0015_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587689-BCUL-PREVIEW-426367_0004.jpg"
"letter_0015_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587689-BCUL-PREVIEW-426367_0005.jpg"

