mf_id = "letter_0469.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0469_001 = "https://www.e-manuscripta.ch/i3f/v20/5346252/info.json"
letter_0469_002 = "https://www.e-manuscripta.ch/i3f/v20/5346253/info.json"
