mf_id = "letter_0397.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Emmie Oprecht"

[mf_data]
letter_0397_001 = "https://www.e-manuscripta.ch/i3f/v20/5219362/info.json"
letter_0397_002 = "https://www.e-manuscripta.ch/i3f/v20/5219363/info.json"
