mf_id = "letter_0451.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0451_001 = "https://www.e-manuscripta.ch/i3f/v20/5346184/info.json"
letter_0451_002 = "https://www.e-manuscripta.ch/i3f/v20/5346185/info.json"
letter_0451_003 = "https://www.e-manuscripta.ch/i3f/v20/5349014/info.json"
letter_0451_004 = "https://www.e-manuscripta.ch/i3f/v20/5349013/info.json"
