mf_id = "letter_0261.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 18.01.1940"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0261_001" = "https://www.monacensia-digital.de/i3f/v20/415326"
"letter_0261_002" = "https://www.monacensia-digital.de/i3f/v20/415327"
