mf_id = "letter_0402.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Ren√©e Schwarzenbach"

[mf_data]
letter_0402_001 = "https://www.e-manuscripta.ch/i3f/v20/5289779/info.json"
letter_0402_002 = "https://www.e-manuscripta.ch/i3f/v20/5289780/info.json"
letter_0402_003 = "https://www.e-manuscripta.ch/i3f/v20/5289781/info.json"
letter_0402_004 = "https://www.e-manuscripta.ch/i3f/v20/5289782/info.json"
