mf_id = "letter_0104.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0104_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0104_001.tif"
"letter_0104_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0104_002.tif"


