mf_id = "letter_0193.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 28.10.1930"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0193_001" = "https://www.monacensia-digital.de/i3f/v20/415764"
"letter_0193_002" = "https://www.monacensia-digital.de/i3f/v20/415765"
