mf_id = "letter_0186.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 22.11.1941"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0186_001" = "https://www.monacensia-digital.de/i3f/v20/415673"
"letter_0186_002" = "https://www.monacensia-digital.de/i3f/v20/415674"
