mf_id = "letter_0244.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 01.1939 [Ende Januar]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0244_001" = "https://www.monacensia-digital.de/i3f/v20/415366"
"letter_0244_002" = "https://www.monacensia-digital.de/i3f/v20/415365"

