mf_id = "letter_0082.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0082_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0082_001.tif"
"letter_0082_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0082_002.tif"
"letter_0082_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0082_003.tif"
"letter_0082_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0082_004.tif"
