mf_id = "letter_0278.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [Mitte Januar 1935]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0278_001" = "https://www.monacensia-digital.de/i3f/v20/415306"
"letter_0278_002" = "https://www.monacensia-digital.de/i3f/v20/415307"


