mf_id = "letter_0075.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0075_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0075_001.tif"
"letter_0075_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0075_002.tif"
"letter_0075_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0075_003.tif"
"letter_0075_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0075_004.tif"

