mf_id = "letter_0428.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Hans Schwarzenbach"

[mf_data]
letter_0428_001 = "https://www.e-manuscripta.ch/i3f/v20/5289953/info.json"
letter_0428_002 = "https://www.e-manuscripta.ch/i3f/v20/5289954/info.json"
