mf_id = "letter_0047.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0047_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587722-BCUL-PREVIEW-426400_0001.jpg"
"letter_0047_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587722-BCUL-PREVIEW-426400_0002.jpg"
"letter_0047_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587722-BCUL-PREVIEW-426400_0003.jpg"
"letter_0047_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587722-BCUL-PREVIEW-426400_0004.jpg"
"letter_0047_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587722-BCUL-PREVIEW-426400_0005.jpg"


