mf_id = "letter_0456.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0456_001 = "https://www.e-manuscripta.ch/i3f/v20/5346202/info.json"
letter_0456_002 = "https://www.e-manuscripta.ch/i3f/v20/5346203/info.json"
