mf_id = "letter_0036.json"
mf_lang = "en"
mf_label = "Télégramme d'Annemarie Schwarzenbach à Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0036_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587711-BCUL-PREVIEW-426389_0001.jpg"
"letter_0036_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587711-BCUL-PREVIEW-426389_0002.jpg"
"letter_0036_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587711-BCUL-PREVIEW-426389_0003.jpg"
"letter_0036_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587711-BCUL-PREVIEW-426389_0004.jpg"
"letter_0036_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587711-BCUL-PREVIEW-426389_0005.jpg"

