mf_id = "letter_0131.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Fueter, Eduard"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0131_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0131_001.tif"
"letter_0131_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0131_002.tif"
