mf_id = "letter_0189.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 24.12.1930"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0189_001" = "https://www.monacensia-digital.de/i3f/v20/415568"
"letter_0189_002" = "https://www.monacensia-digital.de/i3f/v20/415569"
