mf_id = "letter_0434.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Martin HÃ¼rlimann"

[mf_data]
letter_0434_001 = "https://www.e-manuscripta.ch/i3f/v20/5346168/info.json"
letter_0434_002 = "https://www.e-manuscripta.ch/i3f/v20/5346169/info.json"
