
mf_id = "letter_0059.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Boveri, Margret"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0059_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_001.tif"
"letter_0059_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_002.tif"
"letter_0059_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_003.tif"
"letter_0059_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_004.tif"
"letter_0059_005" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_005.tif"
"letter_0059_006" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_006.tif"
"letter_0059_007" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0059_007.tif"
