mf_id = "letter_0427.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Hans Schwarzenbach"

[mf_data]
letter_0427_001 = "https://www.e-manuscripta.ch/i3f/v20/5289948/info.json"
letter_0427_002 = "https://www.e-manuscripta.ch/i3f/v20/5289949/info.json"
