mf_id = "letter_0439.json"
mf_lang = "en"
mf_label = "Briefkarte von Annemarie Schwarzenbach an Robert Faesi"

[mf_data]
letter_0439_001 = "https://www.e-manuscripta.ch/i3f/v20/5346310/info.json"
letter_0439_002 = "https://www.e-manuscripta.ch/i3f/v20/5346311/info.json"
