mf_id = "letter_0472.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0472_001 = "https://www.e-manuscripta.ch/i3f/v20/5346262/info.json"
letter_0472_002 = "https://www.e-manuscripta.ch/i3f/v20/5346263/info.json"
letter_0472_003 = "https://www.e-manuscripta.ch/i3f/v20/5346264/info.json"
letter_0472_004 = "https://www.e-manuscripta.ch/i3f/v20/5346265/info.json"
