mf_id = "letter_0229.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0229_001" = "https://www.monacensia-digital.de/i3f/v20/415712"
"letter_0229_002" = "https://www.monacensia-digital.de/i3f/v20/415713"
"letter_0229_003" = "https://www.monacensia-digital.de/i3f/v20/415714"



