mf_id = "letter_0457.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0457_001 = "https://www.e-manuscripta.ch/i3f/v20/5346204/info.json"
letter_0457_002 = "https://www.e-manuscripta.ch/i3f/v20/5346205/info.json"
letter_0457_003 = "https://www.e-manuscripta.ch/i3f/v20/5346206/info.json"
letter_0457_004 = "https://www.e-manuscripta.ch/i3f/v20/5346207/info.json"
letter_0457_005 = "https://www.e-manuscripta.ch/i3f/v20/5346208/info.json"
letter_0457_006 = "https://www.e-manuscripta.ch/i3f/v20/5346209/info.json"
