mf_id = "letter_0446.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0446_001 = "https://www.e-manuscripta.ch/i3f/v20/5346173/info.json"
letter_0446_002 = "https://www.e-manuscripta.ch/i3f/v20/5346174/info.json"
