mf_id = "letter_0064.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0064_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0064_001.tif"
"letter_0064_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0064_002.tif"
"letter_0064_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0064_003.tif"
"letter_0064_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0064_004.tif"

