mf_id = "letter_0054.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0054_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0001.jpg"
"letter_0054_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0002.jpg"
"letter_0054_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0003.jpg"
"letter_0054_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0004.jpg"
"letter_0054_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0005.jpg"
"letter_0054_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0006.jpg"
"letter_0054_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587729-BCUL-PREVIEW-426407_0007.jpg"

