mf_id = "letter_0117.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Kleiber, Otto"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0117_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0117_001.tif"
"letter_0117_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0117_002.tif"
"letter_0117_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0117_003.tif"
"letter_0117_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0117_004.tif"

