mf_id = "letter_0184.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 1933 [Fr√ºhjahr]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0184_001" = "https://www.monacensia-digital.de/i3f/v20/415782"
"letter_0184_002" = "https://www.monacensia-digital.de/i3f/v20/415783"
