mf_id = "letter_0272.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1934]-07-05"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0272_001" = "https://www.monacensia-digital.de/i3f/v20/415284"
"letter_0272_002" = "https://www.monacensia-digital.de/i3f/v20/415279"


