mf_id = "letter_0403.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach, Suzanne Schwarzenbach an Torgny Ã–hmann"

[mf_data]
letter_0403_001 = "https://www.e-manuscripta.ch/i3f/v20/5289786/info.json"
letter_0403_002 = "https://www.e-manuscripta.ch/i3f/v20/5289787/info.json"
letter_0403_003 = "https://www.e-manuscripta.ch/i3f/v20/5289788/info.json"
letter_0403_004 = "https://www.e-manuscripta.ch/i3f/v20/5289789/info.json"
