mf_id = "letter_0242.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 01.09.1940"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0242_001" = "https://www.monacensia-digital.de/i3f/v20/415338"
"letter_0242_002" = "https://www.monacensia-digital.de/i3f/v20/415339"

