mf_id = "letter_0196.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 31.10.1930 [?]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0196_001" = "https://www.monacensia-digital.de/i3f/v20/415768"
"letter_0196_002" = "https://www.monacensia-digital.de/i3f/v20/415769"
