mf_id = "letter_0293.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1937]-03-05"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`


[mf_data]
"letter_0293_001" = "https://www.monacensia-digital.de/i3f/v20/415387"
"letter_0293_002" = "https://www.monacensia-digital.de/i3f/v20/415386"


