mf_id = "letter_0164.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 06.1941"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0164_001" = "https://www.monacensia-digital.de/i3f/v20/415601"
"letter_0164_002" = "https://www.monacensia-digital.de/i3f/v20/415602"
"letter_0164_003" = "https://www.monacensia-digital.de/i3f/v20/415603"
"letter_0164_004" = "https://www.monacensia-digital.de/i3f/v20/415604"

