mf_id = "letter_0234.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0234_001" = "https://www.monacensia-digital.de/i3f/v20/415726"
"letter_0234_002" = "https://www.monacensia-digital.de/i3f/v20/415727"
"letter_0234_003" = "https://www.monacensia-digital.de/i3f/v20/415728"
"letter_0234_004" = "https://www.monacensia-digital.de/i3f/v20/415729"
"letter_0234_005" = "https://www.monacensia-digital.de/i3f/v20/415730"
"letter_0234_006" = "https://www.monacensia-digital.de/i3f/v20/415731"


