mf_id = "letter_0259.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 15.04.1935"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0259_001" = "https://www.monacensia-digital.de/i3f/v20/415270"

