mf_id = "letter_0411.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Suzanne Ã–hmann-Schwarzenbach"

[mf_data]
letter_0411_001 = "https://www.e-manuscripta.ch/i3f/v20/5289834/info.json"
letter_0411_002 = "https://www.e-manuscripta.ch/i3f/v20/5289835/info.json"
letter_0411_003 = "https://www.e-manuscripta.ch/i3f/v20/5289836/info.json"
letter_0411_004 = "https://www.e-manuscripta.ch/i3f/v20/5289837/info.json"
