mf_id = "letter_0455.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0455_001 = "https://www.e-manuscripta.ch/i3f/v20/5346200/info.json"
letter_0455_002 = "https://www.e-manuscripta.ch/i3f/v20/5346201/info.json"
