mf_id = "letter_0426.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Ren√©e Schwarzenbach"

[mf_data]
letter_0426_001 = "https://www.e-manuscripta.ch/i3f/v20/5289939/info.json"
letter_0426_002 = "https://www.e-manuscripta.ch/i3f/v20/5289940/info.json"
letter_0426_003 = "https://www.e-manuscripta.ch/i3f/v20/5289941/info.json"
letter_0426_004 = "https://www.e-manuscripta.ch/i3f/v20/5289942/info.json"
letter_0426_005 = "https://www.e-manuscripta.ch/i3f/v20/5289943/info.json"
letter_0426_006 = "https://www.e-manuscripta.ch/i3f/v20/5289944/info.json"
