mf_id = "letter_0410.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Ren√©e Schwarzenbach"

[mf_data]
letter_0410_001 = "https://www.e-manuscripta.ch/i3f/v20/5289829/info.json"
letter_0410_002 = "https://www.e-manuscripta.ch/i3f/v20/5289830/info.json"
