mf_id = "letter_0039.json"
mf_lang = "en"
mf_label = "Lettre dactylographiée d'Annemarie Schwarzenbach à Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0039_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587714-BCUL-PREVIEW-426392_0001.jpg"
"letter_0039_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587714-BCUL-PREVIEW-426392_0002.jpg"
"letter_0039_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587714-BCUL-PREVIEW-426392_0003.jpg"
