mf_id = "letter_0406.json"
mf_lang = "en"
mf_label = "Postkarte von Ren√©e Schwarzenbach?, Annemarie Schwarzenbach, Alfred Schwarzenbach, Hans Schwarzenbach an Alfred Schwarzenbach"

[mf_data]
letter_0406_001 = "https://www.e-manuscripta.ch/i3f/v20/5289805/info.json"
letter_0406_002 = "https://www.e-manuscripta.ch/i3f/v20/5289806/info.json"
