mf_id = "letter_0420.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Hans Schwarzenbach"

[mf_data]
letter_0420_001 = "https://www.e-manuscripta.ch/i3f/v20/5289897/info.json"
letter_0420_002 = "https://www.e-manuscripta.ch/i3f/v20/5289898/info.json"
