mf_id = "letter_0216.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0216_001" = "https://www.monacensia-digital.de/i3f/v20/415665"
"letter_0216_002" = "https://www.monacensia-digital.de/i3f/v20/415666"
"letter_0216_003" = "https://www.monacensia-digital.de/i3f/v20/415667"
"letter_0216_004" = "https://www.monacensia-digital.de/i3f/v20/415668"

