mf_id = "letter_0409.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Anita Forrer"

[mf_data]
letter_0409_001 = "https://www.e-manuscripta.ch/i3f/v20/5289824/info.json"
letter_0409_002 = "https://www.e-manuscripta.ch/i3f/v20/5289825/info.json"
