mf_id = "letter_0443.json"
mf_lang = "en"
mf_label = "Brief von Alfred Schwarzenbach an Annemarie Schwarzenbach"

[mf_data]
letter_0443_001 = "https://www.e-manuscripta.ch/i3f/v20/5508018/info.json"
letter_0443_002 = "https://www.e-manuscripta.ch/i3f/v20/5508019/info.json"
