mf_id = "letter_0072.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0072_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0072_001.tif"
"letter_0072_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0072_002.tif"
"letter_0072_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0072_003.tif"
"letter_0072_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0072_004.tif"

