mf_id = "letter_0431.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach (Fritz), Suzanne Ã–hmann-Schwarzenbach an Alfred Schwarzenbach"

[mf_data]
letter_0431_001 = "https://www.e-manuscripta.ch/i3f/v20/5294138/info.json"
letter_0431_002 = "https://www.e-manuscripta.ch/i3f/v20/5294139/info.json"
letter_0431_003 = "https://www.e-manuscripta.ch/i3f/v20/5294140/info.json"
letter_0431_004 = "https://www.e-manuscripta.ch/i3f/v20/5294141/info.json"
