mf_id = "letter_0260.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 17.04.1934"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0260_001" = "https://www.monacensia-digital.de/i3f/v20/415295"
"letter_0260_002" = "https://www.monacensia-digital.de/i3f/v20/415296"

