mf_id = "letter_0171.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 12.1930 [Ende Dez.]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0171_001" = "https://www.monacensia-digital.de/i3f/v20/415648"
"letter_0171_002" = "https://www.monacensia-digital.de/i3f/v20/415649"
"letter_0171_003" = "https://www.monacensia-digital.de/i3f/v20/415650"
