mf_id = "letter_0445.json"
mf_lang = "en"
mf_label = "Brief von Henri Fran√ßois Martin an Annemarie Schwarzenbach"

[mf_data]
letter_0445_001 = "https://www.e-manuscripta.ch/i3f/v20/5508038/info.json"
letter_0445_002 = "https://www.e-manuscripta.ch/i3f/v20/5508039/info.json"
letter_0445_003 = "https://www.e-manuscripta.ch/i3f/v20/5508027/info.json"
letter_0445_004 = "https://www.e-manuscripta.ch/i3f/v20/5508028/info.json"
letter_0445_005 = "https://www.e-manuscripta.ch/i3f/v20/5508029/info.json"
letter_0445_006 = "https://www.e-manuscripta.ch/i3f/v20/5508030/info.json"
letter_0445_007 = "https://www.e-manuscripta.ch/i3f/v20/5508031/info.json"
letter_0445_008 = "https://www.e-manuscripta.ch/i3f/v20/5508032/info.json"
letter_0445_009 = "https://www.e-manuscripta.ch/i3f/v20/5508033/info.json"
letter_0445_010 = "https://www.e-manuscripta.ch/i3f/v20/5508034/info.json"
letter_0445_011 = "https://www.e-manuscripta.ch/i3f/v20/5508035/info.json"
letter_0445_012 = "https://www.e-manuscripta.ch/i3f/v20/5508036/info.json"
