mf_id = "letter_0101.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0101_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0101_001.tif"
"letter_0101_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0101_002.tif"
"letter_0101_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0101_003.tif"
"letter_0101_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0101_004.tif"

