mf_id = "letter_0154.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 02.02.1931"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0154_001" = "https://www.monacensia-digital.de/i3f/v20/415742"
"letter_0154_002" = "https://www.monacensia-digital.de/i3f/v20/415743"
