mf_id = "letter_0250.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 05.05.1937"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0250_001" = "https://www.monacensia-digital.de/i3f/v20/415300"
"letter_0250_002" = "https://www.monacensia-digital.de/i3f/v20/415301"
"letter_0250_003" = "https://www.monacensia-digital.de/i3f/v20/415302"
"letter_0250_004" = "https://www.monacensia-digital.de/i3f/v20/415303"
