mf_id = "letter_0415.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Torgny Ã–hmann"

[mf_data]
letter_0415_001 = "https://www.e-manuscripta.ch/i3f/v20/5289860/info.json"
letter_0415_002 = "https://www.e-manuscripta.ch/i3f/v20/5289861/info.json"
letter_0415_003 = "https://www.e-manuscripta.ch/i3f/v20/5289862/info.json"
letter_0415_004 = "https://www.e-manuscripta.ch/i3f/v20/5289863/info.json"
letter_0415_005 = "https://www.e-manuscripta.ch/i3f/v20/5289864/info.json"
letter_0415_006 = "https://www.e-manuscripta.ch/i3f/v20/5289865/info.json"
