mf_id = "letter_0447.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0447_001 = "https://www.e-manuscripta.ch/i3f/v20/5346175/info.json"
letter_0447_002 = "https://www.e-manuscripta.ch/i3f/v20/5346176/info.json"
