mf_id = "letter_0398.json"
mf_lang = "en"
mf_label = "Verlagsvertrag zwischen Annemarie Schwarzenbach und Rascher und Cie."

[mf_data]
letter_0398_001 = "https://www.e-manuscripta.ch/i3f/v20/5219377/info.json"
letter_0398_002 = "https://www.e-manuscripta.ch/i3f/v20/5219378/info.json"
