mf_id = "letter_0056.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0056_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0001.jpg"
"letter_0056_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0002.jpg"
"letter_0056_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0003.jpg"
"letter_0056_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0004.jpg"
"letter_0056_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0005.jpg"
"letter_0056_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0006.jpg"
"letter_0056_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587731-BCUL-PREVIEW-426409_0007.jpg"


