mf_id = "letter_0249.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 04.11.1934"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0249_001" = "https://www.monacensia-digital.de/i3f/v20/415349"
"letter_0249_002" = "https://www.monacensia-digital.de/i3f/v20/415350"
