mf_id = "smallform_0436.json"
mf_lang = "en"
mf_label = "KÃ¼nstler und Staat"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"smallform_0436_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0436_001.tif/info.json"
"smallform_0436_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0436_002.tif/info.json"