mf_id = "smallform_0631.json"
mf_lang = "en"
mf_label = "Der Winterabend, 12./13.12.1939"

[mf_data]
smallform_0631_001 = "https://www.e-manuscripta.ch/i3f/v20/5346315/info.json"
smallform_0631_002 = "https://www.e-manuscripta.ch/i3f/v20/5346316/info.json"
smallform_0631_003 = "https://www.e-manuscripta.ch/i3f/v20/5346317/info.json"
smallform_0631_004 = "https://www.e-manuscripta.ch/i3f/v20/5346318/info.json"
smallform_0631_005 = "https://www.e-manuscripta.ch/i3f/v20/5346319/info.json"
smallform_0631_006 = "https://www.e-manuscripta.ch/i3f/v20/5346320/info.json"
