mf_id = "smallform_0229.json"
mf_lang = "en"
mf_label = "Baltisches Tagebuch III: Neue Hauptst√§dte"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"smallform_0229_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0229_001.tif/info.json"
