mf_id = "smallform_0016.json"
mf_lang = "en"
mf_label = "«Ola Langerud in der Stadt». Von Marise [sic! eigt. Marie] Hamsun"

[mf_data]
"smallform_0016_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0016_001.png/info.json"