mf_id = "smallform_0633.json"
mf_lang = "en"
mf_label = "Die tote Stunde, 1939-12-15"

[mf_data]
smallform_0633_001 = "https://www.e-manuscripta.ch/i3f/v20/5346325/info.json"
smallform_0633_002 = "https://www.e-manuscripta.ch/i3f/v20/5346326/info.json"
smallform_0633_003 = "https://www.e-manuscripta.ch/i3f/v20/5346327/info.json"
smallform_0633_004 = "https://www.e-manuscripta.ch/i3f/v20/5346328/info.json"
