mf_id = "smallform_0634.json"
mf_lang = "en"
mf_label = "Die menschliche Landschaft, 16.-18.12.1939"

[mf_data]
smallform_0634_001 = "https://www.e-manuscripta.ch/i3f/v20/5346329/info.json"
smallform_0634_002 = "https://www.e-manuscripta.ch/i3f/v20/5346330/info.json"
smallform_0634_003 = "https://www.e-manuscripta.ch/i3f/v20/5346331/info.json"
smallform_0634_004 = "https://www.e-manuscripta.ch/i3f/v20/5346332/info.json"
smallform_0634_005 = "https://www.e-manuscripta.ch/i3f/v20/5346333/info.json"
smallform_0634_006 = "https://www.e-manuscripta.ch/i3f/v20/5346334/info.json"
smallform_0634_007 = "https://www.e-manuscripta.ch/i3f/v20/5346335/info.json"
smallform_0634_008 = "https://www.e-manuscripta.ch/i3f/v20/5346336/info.json"
