mf_id = "letter_0022.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0022_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587696-BCUL-PREVIEW-426374_0001.jpg"
"letter_0022_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587696-BCUL-PREVIEW-426374_0002.jpg"
"letter_0022_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587696-BCUL-PREVIEW-426374_0003.jpg"
"letter_0022_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587696-BCUL-PREVIEW-426374_0004.jpg"
"letter_0022_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587696-BCUL-PREVIEW-426374_0005.jpg"

