mf_id = "letter_0263.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 21.09.1935"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0263_001" = "https://www.monacensia-digital.de/i3f/v20/415369"

