mf_id = "letter_0437.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Jakob Job"

[mf_data]
letter_0437_001 = "https://www.e-manuscripta.ch/i3f/v20/5346300/info.json"
letter_0437_002 = "https://www.e-manuscripta.ch/i3f/v20/5346301/info.json"
