mf_id = "letter_0283.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1937]-05-28"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0283_001" = "https://www.monacensia-digital.de/i3f/v20/415333/info.json"
"letter_0283_002" = "https://www.monacensia-digital.de/i3f/v20/415334/info.json"


