mf_id = "letter_0093.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0093_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0093_001.tif"
"letter_0093_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0093_002.tif"
"letter_0093_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0093_003.tif"
"letter_0093_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0093_004.tif"
"letter_0093_005" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0093_005.tif"
"letter_0093_006" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0093_006.tif"


