mf_id = "letter_0019.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0019_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0001.jpg"
"letter_0019_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0002.jpg"
"letter_0019_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0003.jpg"
"letter_0019_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0004.jpg"
"letter_0019_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0005.jpg"
"letter_0019_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0006.jpg"
"letter_0019_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587693-BCUL-PREVIEW-426371_0007.jpg"

