mf_id = "letter_0257.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 11.09.1937"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0257_001" = "https://www.monacensia-digital.de/i3f/v20/415381"
"letter_0257_002" = "https://www.monacensia-digital.de/i3f/v20/415380"
"letter_0257_003" = "https://www.monacensia-digital.de/i3f/v20/415379"
"letter_0257_004" = "https://www.monacensia-digital.de/i3f/v20/415378"
