mf_id = "letter_0465.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0465_001 = "https://www.e-manuscripta.ch/i3f/v20/5346236/info.json"
letter_0465_002 = "https://www.e-manuscripta.ch/i3f/v20/5346237/info.json"
