mf_id = "letter_0188.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 24.02.1933"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0188_001" = "https://www.monacensia-digital.de/i3f/v20/415780"
"letter_0188_002" = "https://www.monacensia-digital.de/i3f/v20/415781"
