mf_id = "letter_0237.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0237_001" = "https://www.monacensia-digital.de/i3f/v20/415738"
"letter_0237_002" = "https://www.monacensia-digital.de/i3f/v20/415739"


