mf_id = "letter_0133.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Henne, Rolf"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0133_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0133_001.tif"
"letter_0133_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0133_002.tif"
"letter_0133_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0133_003.tif"
"letter_0133_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0133_004.tif"