mf_id = "letter_0035.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0035_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587710-BCUL-PREVIEW-426388_0001.jpg"
"letter_0035_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587710-BCUL-PREVIEW-426388_0002.jpg"
"letter_0035_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587710-BCUL-PREVIEW-426388_0003.jpg"
"letter_0035_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587710-BCUL-PREVIEW-426388_0004.jpg"
"letter_0035_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587710-BCUL-PREVIEW-426388_0005.jpg"
