mf_id = "letter_0470.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0470_001 = "https://www.e-manuscripta.ch/i3f/v20/5346254/info.json"
letter_0470_002 = "https://www.e-manuscripta.ch/i3f/v20/5346255/info.json"
