mf_id = "letter_0247.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 02.09.1942"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0247_001" = "https://www.monacensia-digital.de/i3f/v20/415389"
"letter_0247_002" = "https://www.monacensia-digital.de/i3f/v20/415388"
