mf_id = "letter_0207.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0207_001" = "https://www.monacensia-digital.de/i3f/v20/415633"
"letter_0207_002" = "https://www.monacensia-digital.de/i3f/v20/415634"
