mf_id = "letter_0449.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0449_001 = "https://www.e-manuscripta.ch/i3f/v20/5351559/info.json"
letter_0449_002 = "https://www.e-manuscripta.ch/i3f/v20/5346181/info.json"
