mf_id = "letter_0274.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1935]-05-19"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0274_001" = "https://www.monacensia-digital.de/i3f/v20/415282"
"letter_0274_002" = "https://www.monacensia-digital.de/i3f/v20/415283"


