mf_id = "letter_0425.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Torgny Ã–hmann"

[mf_data]
letter_0425_001 = "https://www.e-manuscripta.ch/i3f/v20/5289934/info.json"
letter_0425_002 = "https://www.e-manuscripta.ch/i3f/v20/5289935/info.json"
