mf_id = "letter_0286.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1934-05]-7"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0286_001" = "https://www.monacensia-digital.de/i3f/v20/415345"
"letter_0286_002" = "https://www.monacensia-digital.de/i3f/v20/415346"



