mf_id = "letter_0452.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0452_001 = "https://www.e-manuscripta.ch/i3f/v20/5346188/info.json"
letter_0452_002 = "https://www.e-manuscripta.ch/i3f/v20/5346189/info.json"
letter_0452_003 = "https://www.e-manuscripta.ch/i3f/v20/5346190/info.json"
letter_0452_004 = "https://www.e-manuscripta.ch/i3f/v20/5346191/info.json"
letter_0452_005 = "https://www.e-manuscripta.ch/i3f/v20/5346193/info.json"
letter_0452_006 = "https://www.e-manuscripta.ch/i3f/v20/5346192/info.json"
letter_0452_007 = "https://www.e-manuscripta.ch/i3f/v20/5346195/info.json"
letter_0452_008 = "https://www.e-manuscripta.ch/i3f/v20/5349012/info.json"
