mf_id = "letter_0458.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0458_001 = "https://www.e-manuscripta.ch/i3f/v20/5346210/info.json"
letter_0458_002 = "https://www.e-manuscripta.ch/i3f/v20/5346211/info.json"
letter_0458_003 = "https://www.e-manuscripta.ch/i3f/v20/5346212/info.json"
letter_0458_004 = "https://www.e-manuscripta.ch/i3f/v20/5351560/info.json"
letter_0458_005 = "https://www.e-manuscripta.ch/i3f/v20/5351561/info.json"
letter_0458_006 = "https://www.e-manuscripta.ch/i3f/v20/5346213/info.json"
