mf_id = "letter_0284.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [Anfang Januar 1937]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0284_001" = "https://www.monacensia-digital.de/i3f/v20/415342"



