mf_id = "letter_0030.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0030_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587705-BCUL-PREVIEW-426719_0001.jpg"
"letter_0030_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587705-BCUL-PREVIEW-426719_0002.jpg"
"letter_0030_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587705-BCUL-PREVIEW-426719_0003.jpg"
"letter_0030_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587705-BCUL-PREVIEW-426719_0004.jpg"
"letter_0030_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587705-BCUL-PREVIEW-426719_0005.jpg"






