mf_id = "letter_0099.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0099_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0099_001.tif"
"letter_0099_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0099_002.tif"
"letter_0099_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0099_003.tif"
"letter_0099_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0099_004.tif"

