mf_id = "letter_0429.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Suzanne Ã–hmann-Schwarzenbach"

[mf_data]
letter_0429_001 = "https://www.e-manuscripta.ch/i3f/v20/5289958/info.json"
letter_0429_002 = "https://www.e-manuscripta.ch/i3f/v20/5289959/info.json"
