mf_id = "letter_0404.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Ren√©e Schwarzenbach"

[mf_data]
letter_0404_001 = "https://www.e-manuscripta.ch/i3f/v20/5289793/info.json"
letter_0404_002 = "https://www.e-manuscripta.ch/i3f/v20/5289794/info.json"
