mf_id = "letter_0394.json"
mf_lang = "en"
mf_label = "Ansichtskarte von Annemarie Schwarzenbach an Manuel Gasser"

[mf_data]
letter_0394_001 = "https://www.e-manuscripta.ch/i3f/v20/5219169/info.json"
letter_0394_002 = "https://www.e-manuscripta.ch/i3f/v20/5219168/info.json"
