mf_id = "letter_0146.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Seelig, Carl"

[mf_data]
"letter_0146_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0146_001.tif"
"letter_0146_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0146_002.tif"
