mf_id = "letter_0391.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Manuel Gasser"

[mf_data]
letter_0391_001 = "https://www.e-manuscripta.ch/i3f/v20/5228633/info.json"
letter_0391_002 = "https://www.e-manuscripta.ch/i3f/v20/5219071/info.json"
letter_0391_003 = "https://www.e-manuscripta.ch/i3f/v20/5228634/info.json"
letter_0391_004 = "https://www.e-manuscripta.ch/i3f/v20/5219072/info.json"
