mf_id = "letter_0005.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

[mf_data]
"letter_0005_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587680-BCUL-PREVIEW-426358_0001.jpg"
"letter_0005_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587680-BCUL-PREVIEW-426358_0002.jpg"
"letter_0005_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587680-BCUL-PREVIEW-426358_0003.jpg"
"letter_0005_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587680-BCUL-PREVIEW-426358_0004.jpg"
"letter_0005_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587680-BCUL-PREVIEW-426358_0005.jpg"
