mf_id = "letter_0048.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0048_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587723-BCUL-PREVIEW-426401_0001.jpg"
"letter_0048_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587723-BCUL-PREVIEW-426401_0002.jpg"
"letter_0048_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587723-BCUL-PREVIEW-426401_0003.jpg"


