mf_id = "letter_0419.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Annigna Godly"

[mf_data]
letter_0419_001 = "https://www.e-manuscripta.ch/i3f/v20/5289890/info.json"
letter_0419_002 = "https://www.e-manuscripta.ch/i3f/v20/5289891/info.json"
letter_0419_003 = "https://www.e-manuscripta.ch/i3f/v20/5289892/info.json"
letter_0419_004 = "https://www.e-manuscripta.ch/i3f/v20/5289893/info.json"
