mf_id = "letter_0441.json"
mf_lang = "en"
mf_label = "Brief von Maria Waser an Annemarie Schwarzenbach"

[mf_data]
letter_0441_001 = "https://www.e-manuscripta.ch/i3f/v20/5508023/info.json"
letter_0441_002 = "https://www.e-manuscripta.ch/i3f/v20/5508024/info.json"
