mf_id = "letter_0144.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Th√ºrer, Georg"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0144_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0144_001.tif"
"letter_0144_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0144_002.tif"
