mf_id = "letter_0448.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0448_001 = "https://www.e-manuscripta.ch/i3f/v20/5346177/info.json"
letter_0448_002 = "https://www.e-manuscripta.ch/i3f/v20/5346178/info.json"
letter_0448_003 = "https://www.e-manuscripta.ch/i3f/v20/5346179/info.json"
letter_0448_004 = "https://www.e-manuscripta.ch/i3f/v20/5346180/info.json"
