mf_id = "letter_0162.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 06.01.1931"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0162_001" = "https://www.monacensia-digital.de/i3f/v20/415550"
"letter_0162_002" = "https://www.monacensia-digital.de/i3f/v20/415551"
