mf_id = "letter_0043.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0043_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587718-BCUL-PREVIEW-426396_0001.jpg"
"letter_0043_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587718-BCUL-PREVIEW-426396_0002.jpg"
"letter_0043_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587718-BCUL-PREVIEW-426396_0003.jpg"
"letter_0043_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587718-BCUL-PREVIEW-426396_0004.jpg"
"letter_0043_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587718-BCUL-PREVIEW-426396_0005.jpg"
