mf_id = "letter_0111.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0111_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0111_001.tif"
"letter_0111_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0111_002.tif"

