mf_id = "letter_0122.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Kleiber, Otto"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0122_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0122_001.tif"
"letter_0122_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0122_002.tif"
