
mf_id = "letter_0014.json"
mf_lang = "en"
mf_label = "Carte postale d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0014_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587688-BCUL-PREVIEW-426366_0001.jpg"
"letter_0014_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587688-BCUL-PREVIEW-426366_0002.jpg"
"letter_0014_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587688-BCUL-PREVIEW-426366_0003.jpg"
