mf_id = "letter_0280.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0280_001" = "https://www.monacensia-digital.de/i3f/v20/415310"
"letter_0280_002" = "https://www.monacensia-digital.de/i3f/v20/415311"


