mf_id = "letter_0083.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0083_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0083_001.tif"
"letter_0083_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0083_002.tif"
"letter_0083_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0083_003.tif"
"letter_0083_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0083_004.tif"
"letter_0083_005" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0083_005.tif"
"letter_0083_006" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0083_006.tif"
