mf_id = "letter_0432.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Alfred Schwarzenbach"

[mf_data]
letter_0432_001 = "https://www.e-manuscripta.ch/i3f/v20/5294145/info.json"
letter_0432_002 = "https://www.e-manuscripta.ch/i3f/v20/5294146/info.json"
