mf_id = "letter_0264.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 23.07.1940"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0264_001" = "https://www.monacensia-digital.de/i3f/v20/415340"
"letter_0264_002" = "https://www.monacensia-digital.de/i3f/v20/415341"


