mf_id = "letter_0055.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0055_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0001.jpg"
"letter_0055_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0002.jpg"
"letter_0055_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0003.jpg"
"letter_0055_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0004.jpg"
"letter_0055_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0005.jpg"
"letter_0055_006" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0006.jpg"
"letter_0055_007" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587730-BCUL-PREVIEW-426408_0007.jpg"


