mf_id = "letter_0057.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0057_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587732-BCUL-PREVIEW-426410_0001.jpg"
"letter_0057_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587732-BCUL-PREVIEW-426410_0002.jpg"
"letter_0057_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587732-BCUL-PREVIEW-426410_0003.jpg"


