mf_id = "letter_0423.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Suzanne Ã–hmann-Schwarzenbach"

[mf_data]
letter_0423_001 = "https://www.e-manuscripta.ch/i3f/v20/5289914/info.json"
letter_0423_002 = "https://www.e-manuscripta.ch/i3f/v20/5289915/info.json"
letter_0423_003 = "https://www.e-manuscripta.ch/i3f/v20/5289916/info.json"
letter_0423_004 = "https://www.e-manuscripta.ch/i3f/v20/5289917/info.json"
