mf_id = "letter_0058.json"
mf_lang = "en"
mf_label = "Lettre d'Annemarie Schwarzenbach Ã  Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0058_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587733-BCUL-PREVIEW-426411_0001.jpg"
"letter_0058_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587733-BCUL-PREVIEW-426411_0002.jpg"
"letter_0058_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587733-BCUL-PREVIEW-426411_0003.jpg"
"letter_0058_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587733-BCUL-PREVIEW-426411_0004.jpg"
"letter_0058_005" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587733-BCUL-PREVIEW-426411_0005.jpg"



