mf_id = "letter_0262.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 21.06.1940"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0262_001" = "https://www.monacensia-digital.de/i3f/v20/415328"
"letter_0262_002" = "https://www.monacensia-digital.de/i3f/v20/415329"
"letter_0262_003" = "https://www.monacensia-digital.de/i3f/v20/415330"
