mf_id = "letter_0126.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Fueter, Eduard"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0126_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0126_001.tif"
"letter_0126_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0126_002.tif"
"letter_0126_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0126_003.tif"
"letter_0126_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0126_004.tif"
