mf_id = "letter_0444.json"
mf_lang = "en"
mf_label = "Brief von Henri Fran√ßois Martin an Annemarie Schwarzenbach"

[mf_data]
letter_0444_001 = "https://www.e-manuscripta.ch/i3f/v20/5508048/info.json"
letter_0444_002 = "https://www.e-manuscripta.ch/i3f/v20/5508049/info.json"
letter_0444_003 = "https://www.e-manuscripta.ch/i3f/v20/5508050/info.json"
letter_0444_004 = "https://www.e-manuscripta.ch/i3f/v20/5508051/info.json"
letter_0444_005 = "https://www.e-manuscripta.ch/i3f/v20/5508052/info.json"
letter_0444_006 = "https://www.e-manuscripta.ch/i3f/v20/5508053/info.json"
letter_0444_007 = "https://www.e-manuscripta.ch/i3f/v20/5508054/info.json"
letter_0444_008 = "https://www.e-manuscripta.ch/i3f/v20/5508055/info.json"
letter_0444_009 = "https://www.e-manuscripta.ch/i3f/v20/5508056/info.json"
letter_0444_010 = "https://www.e-manuscripta.ch/i3f/v20/5508057/info.json"
