mf_id = "letter_0100.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0100_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0100_001.tif"
"letter_0100_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0100_002.tif"
"letter_0100_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0100_003.tif"


