mf_id = "letter_0270.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1935]-05-19"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0270_001" = "https://www.monacensia-digital.de/i3f/v20/415269"
"letter_0270_002" = "https://www.monacensia-digital.de/i3f/v20/415268"
"letter_0270_003" = "https://www.monacensia-digital.de/i3f/v20/415267"
"letter_0270_004" = "https://www.monacensia-digital.de/i3f/v20/415266"
"letter_0270_005" = "https://www.monacensia-digital.de/i3f/v20/415265"
"letter_0270_006" = "https://www.monacensia-digital.de/i3f/v20/415264"

