mf_id = "letter_0462.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0462_001 = "https://www.e-manuscripta.ch/i3f/v20/5346226/info.json"
letter_0462_002 = "https://www.e-manuscripta.ch/i3f/v20/5346227/info.json"
