mf_id = "letter_0421.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Ren√©e Schwarzenbach"

[mf_data]
letter_0421_001 = "https://www.e-manuscripta.ch/i3f/v20/5289902/info.json"
letter_0421_002 = "https://www.e-manuscripta.ch/i3f/v20/5289903/info.json"
