mf_id = "letter_0105.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Burckhardt, Carl Jacob"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0105_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_001.tif"
"letter_0105_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_002.tif"
"letter_0105_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_003.tif"
"letter_0105_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_004.tif"
"letter_0105_005" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_005.tif"
"letter_0105_006" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_006.tif"
"letter_0105_007" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_007.tif"
"letter_0105_008" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_008.tif"
"letter_0105_009" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_009.tif"
"letter_0105_010" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_010.tif"
"letter_0105_011" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_011.tif"
"letter_0105_012" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0105_012.tif"

