mf_id = "letter_0266.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 28.01.1941"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0266_001" = "https://www.monacensia-digital.de/i3f/v20/415257"
"letter_0266_002" = "https://www.monacensia-digital.de/i3f/v20/415256"
"letter_0266_003" = "https://www.monacensia-digital.de/i3f/v20/415255"
"letter_0266_004" = "https://www.monacensia-digital.de/i3f/v20/415254"

