mf_id = "letter_0080.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0080_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0080_001.tif"
"letter_0080_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0080_002.tif"
"letter_0080_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0080_003.tif"
"letter_0080_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0080_004.tif"
"letter_0080_005" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0080_005.tif"
"letter_0080_006" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0080_006.tif"
