mf_id = "letter_0459.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0459_001 = "https://www.e-manuscripta.ch/i3f/v20/5346214/info.json"
letter_0459_002 = "https://www.e-manuscripta.ch/i3f/v20/5346215/info.json"
