mf_id = "letter_0066.json"
mf_lang = "en"
mf_label = "Schwarzenbach, Annemarie an Breslauer, Marianne"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0066_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0066_001.tif"
"letter_0066_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0066_002.tif"
"letter_0066_003" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0066_003.tif"
"letter_0066_004" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/letter_0066_004.tif"

