mf_id = "letter_0408.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Hans Schwarzenbach"

[mf_data]
letter_0408_001 = "https://www.e-manuscripta.ch/i3f/v20/5289819/info.json"
letter_0408_002 = "https://www.e-manuscripta.ch/i3f/v20/5289820/info.json"
