mf_id = "letter_0407.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Hans Schwarzenbach"

[mf_data]
letter_0407_001 = "https://www.e-manuscripta.ch/i3f/v20/5289810/info.json"
letter_0407_002 = "https://www.e-manuscripta.ch/i3f/v20/5289811/info.json"
letter_0407_003 = "https://www.e-manuscripta.ch/i3f/v20/5289812/info.json"
letter_0407_004 = "https://www.e-manuscripta.ch/i3f/v20/5289813/info.json"
letter_0407_005 = "https://www.e-manuscripta.ch/i3f/v20/5289814/info.json"
letter_0407_006 = "https://www.e-manuscripta.ch/i3f/v20/5289815/info.json"
