mf_id = "letter_0152.json"
mf_lang = "en"
mf_label = "Brief von Erika Mann an Annemarie Schwarzenbach, 01.05.1942"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0152_001" = "https://www.monacensia-digital.de/i3f/v20/57199"
"letter_0152_002" = "https://www.monacensia-digital.de/i3f/v20/57200"
"letter_0152_003" = "https://www.monacensia-digital.de/i3f/v20/57201"
"letter_0152_004" = "https://www.monacensia-digital.de/i3f/v20/57202"
