mf_id = "letter_0282.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1938]-07-30"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0282_001" = "https://www.monacensia-digital.de/i3f/v20/415319/info.json"



