mf_id = "letter_0474.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0474_001 = "https://www.e-manuscripta.ch/i3f/v20/5346272/info.json"
letter_0474_002 = "https://www.e-manuscripta.ch/i3f/v20/5346273/info.json"
letter_0474_003 = "https://www.e-manuscripta.ch/i3f/v20/5346274/info.json"
letter_0474_004 = "https://www.e-manuscripta.ch/i3f/v20/5346275/info.json"
