mf_id = "letter_0044.json"
mf_lang = "en"
mf_label = "Lettre dactylographiée d'Annemarie Schwarzenbach à Claude Bourdet"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0044_001" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587719-BCUL-PREVIEW-426397_0001.jpg"
"letter_0044_002" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587719-BCUL-PREVIEW-426397_0002.jpg"
"letter_0044_003" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587719-BCUL-PREVIEW-426397_0003.jpg"
"letter_0044_004" = "https://patrinum.ch/nanna/api/multimedia/image/v2/recid:587719-BCUL-PREVIEW-426397_0004.jpg"
