mf_id = "letter_0253.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 08.04.1933"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0253_001" = "https://www.monacensia-digital.de/i3f/v20/415298"
"letter_0253_002" = "https://www.monacensia-digital.de/i3f/v20/415299"

