mf_id = "letter_0436.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Jakob Job"

[mf_data]
letter_0436_001 = "https://www.e-manuscripta.ch/i3f/v20/5346295/info.json"
letter_0436_002 = "https://www.e-manuscripta.ch/i3f/v20/5346296/info.json"
