mf_id = "letter_0245.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, 02.06.1937"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0245_001" = "https://www.monacensia-digital.de/i3f/v20/415403"
"letter_0245_002" = "https://www.monacensia-digital.de/i3f/v20/415402"
"letter_0245_003" = "https://www.monacensia-digital.de/i3f/v20/415401"
"letter_0245_004" = "https://www.monacensia-digital.de/i3f/v20/415400"
"letter_0245_005" = "https://www.monacensia-digital.de/i3f/v20/415399"
"letter_0245_006" = "https://www.monacensia-digital.de/i3f/v20/415398"

