mf_id = "letter_0450.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0450_001 = "https://www.e-manuscripta.ch/i3f/v20/5346182/info.json"
letter_0450_002 = "https://www.e-manuscripta.ch/i3f/v20/5346183/info.json"
