mf_id = "letter_0453.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0453_001 = "https://www.e-manuscripta.ch/i3f/v20/5346196/info.json"
letter_0453_002 = "https://www.e-manuscripta.ch/i3f/v20/5346197/info.json"
