mf_id = "letter_0473.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Max Rascher"

[mf_data]
letter_0473_001 = "https://www.e-manuscripta.ch/i3f/v20/5346260/info.json"
letter_0473_002 = "https://www.e-manuscripta.ch/i3f/v20/5346261/info.json"
letter_0473_003 = "https://www.e-manuscripta.ch/i3f/v20/5346270/info.json"
letter_0473_004 = "https://www.e-manuscripta.ch/i3f/v20/5346271/info.json"
