mf_id = "letter_0182.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 1931 [Herbst]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0182_001" = "https://www.monacensia-digital.de/i3f/v20/415661"
