mf_id = "letter_0438.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Martin HÃ¼rlimann"

[mf_data]
letter_0438_001 = "https://www.e-manuscripta.ch/i3f/v20/5346305/info.json"
letter_0438_002 = "https://www.e-manuscripta.ch/i3f/v20/5346306/info.json"
