mf_id = "letter_0192.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Erika Mann, 26.12.1931"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`
[mf_data]
"letter_0192_001" = "https://www.monacensia-digital.de/i3f/v20/415570"
"letter_0192_002" = "https://www.monacensia-digital.de/i3f/v20/415571"
"letter_0192_003" = "https://www.monacensia-digital.de/i3f/v20/415572"
