mf_id = "letter_0467.json"
mf_lang = "en"
mf_label = "Brief von Max Rascher an Annemarie Schwarzenbach"

[mf_data]
letter_0467_001 = "https://www.e-manuscripta.ch/i3f/v20/5346242/info.json"
letter_0467_002 = "https://www.e-manuscripta.ch/i3f/v20/5346243/info.json"
