mf_id = "letter_0476.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Klaus Mann, [1938-08-03]"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"letter_0476_001" = "https://www.monacensia-digital.de/i3f/v20/415320/info.json"
"letter_0476_002" = "https://www.monacensia-digital.de/i3f/v20/415321/info.json"


