mf_id = "letter_0400.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Suzanne Ã–hmann-Schwarzenbach"

[mf_data]
letter_0400_001 = "https://www.e-manuscripta.ch/i3f/v20/5289767/info.json"
letter_0400_002 = "https://www.e-manuscripta.ch/i3f/v20/5289768/info.json"
