mf_id = "letter_0392.json"
mf_lang = "en"
mf_label = "Brief von Annemarie Schwarzenbach an Emmie Oprecht"

[mf_data]
letter_0392_001 = "https://www.e-manuscripta.ch/i3f/v20/5219095/info.json"
letter_0392_002 = "https://www.e-manuscripta.ch/i3f/v20/5219096/info.json"
