mf_id = "smallform_0632.json"
mf_lang = "en"
mf_label = "Der Aufbruch, die nie bereute Stunde ..., 1939-12-14"

[mf_data]
smallform_0632_001 = "https://www.e-manuscripta.ch/i3f/v20/5346321/info.json"
smallform_0632_002 = "https://www.e-manuscripta.ch/i3f/v20/5346322/info.json"
smallform_0632_003 = "https://www.e-manuscripta.ch/i3f/v20/5346323/info.json"
smallform_0632_004 = "https://www.e-manuscripta.ch/i3f/v20/5346324/info.json"
