mf_id = "smallform_0329.json"
mf_lang = "en"
mf_label = "Die TÃ¶pfer von Istalif"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"smallform_0329_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0329_001.tif/info.json"
"smallform_0329_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0329_002.tif/info.json"