mf_id = "smallform_0367.json"
mf_lang = "en"
mf_label = "Afghanistan und der Krieg"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"smallform_0367_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0367_001.tif/info.json"