mf_id = "smallform_0206.json"
mf_lang = "en"
mf_label = "'Die Reise nach Pittsburgh (Schlu√ü)'"

# IIIF image links as a sequence of key/value pairs under `[mf_data]`

[mf_data]
"smallform_0206_001" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0206_001.tif/info.json"
"smallform_0206_002" = "https://iiif.ub.unibe.ch/image/v3/schwarzenbach/smallform_0206_002.tif/info.json"